# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SupportClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SupportClient
  pod 'BSImagePicker'
  pod 'DZNEmptyDataSet', :git=> 'https://github.com/cuappdev/DZNEmptyDataSet.git'

end
