platform :ios, '13.0'

target 'PatchKit_Example' do
  pod 'PatchKit', :path => '../'

  use_frameworks!

  # Pods for SupportClient
  pod 'BSImagePicker'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  
  target 'PatchKit_Tests' do
    inherit! :search_paths

    
  end
end
